# Generated by Django 5.2.15 on 2026-08-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='busca_norm',
            field=models.CharField(blank=True, db_index=True, max_length=400),
        ),
    ]
