# Generated by Django 5.2.15 on 2026-08-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0003_povoar_busca_norm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='link_escudo',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='nome_escudo',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='passe',
        ),
    ]
