# Generated by Django 5.2.15 on 2026-08-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0004_remove_jogador_link_escudo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChaveApiExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Quem usa esta chave — ex.: "Painel de Campeonatos X".', max_length=120, verbose_name='nome')),
                ('token', models.CharField(blank=True, editable=False, max_length=64, unique=True, verbose_name='token')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
            ],
            options={
                'verbose_name': 'chave de API externa',
                'verbose_name_plural': 'chaves de API externa',
                'ordering': ['nome'],
            },
        ),
    ]
